//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEducationPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationPortalEntities : DbContext
    {
        public EducationPortalEntities()
            : base("name=EducationPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact_Data> Contact_Data { get; set; }
        public virtual DbSet<RegisterData> RegisterDatas { get; set; }
        public virtual DbSet<StudentData> StudentDatas { get; set; }
        public virtual DbSet<StudyData> StudyDatas { get; set; }
    }
}
